# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-14
spec:
  selector:
    matchLabels:
      app: module-14
  replicas: 1
  template:
    metadata:
      labels:
        app: module-14
    spec:
      containers:
        - name: todo-app
          image: todo-app:prod-1.0
          imagePullPolicy: Never
          env:
          - name: FLASK_APP
            value: "todo_app/app"
          - name: FLASK_ENV
            value: "production"
          - name: LOG_LEVEL
            value: "INFO"
          - name: LOGGLY_TOKEN
            value: "8f4d8bf1-80ab-450f-b11b-f9a6c973b6f5"
          - name: SECRET_KEY
            value: "secret-key"
          - name: DB_CONNECTION_URL
            value: "mongodb+srv://devops:mongo123@cluster0.0pkb8.mongodb.net/myFirstDatabase?w=majority"
          - name: TODO_DB_NAME
            value: "todo"
          - name: TODO_BOARD_ID
            value: "609542268e084d62bd913af7"
          - name: CLIENT_ID
            value: "bafdb05b83ed4c1f7b75"
          - name: CLIENT_SECRET
            value: "a5fbe3b937c581f018d386b86dc9d4b11d15de97"
          - name: OAUTHLIB_INSECURE_TRANSPORT
            value: "1"
          ports:
          - containerPort: 80