name: To Do app CI & CD
#on: [push, pull_request]
on: [push]

jobs:
  test:
    name: build docker test image and run tests
    runs-on: ubuntu-latest
    env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DB_CONNECTION_URL: ${{ secrets.DB_CONNECTION_URL }}
        TODO_DB_NAME: todo
    steps:
    - uses: actions/checkout@v2
    - run: docker build --target test --tag my-test-image .
    - run: docker run --env-file .env.test my-test-image tests
    - run: docker run --env SECRET_KEY --env DB_CONNECTION_URL --env TODO_DB_NAME my-test-image tests_e2e

  push:
    name: build docker production image and push to docker hub
    runs-on: ubuntu-latest
    needs: test
    env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
    - run: echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - run: docker build --target production --tag $DOCKER_HUB_USERNAME/todo:${{ github.sha }} --tag $DOCKER_HUB_USERNAME/todo:latest .
    - run: docker push $DOCKER_HUB_USERNAME/todo:${{ github.sha }}
    - run: docker push $DOCKER_HUB_USERNAME/todo:latest

  deploy:
    name: deploy production image to heroku and azure
    runs-on: ubuntu-latest
    env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    needs: push
    # if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request' # include this line if you want to limit the deployment to the master branch
    steps:
      - uses: actions/checkout@v2
      - run: docker login --username=_ --password=$(heroku auth:token) registry.heroku.com
      - run: docker pull $DOCKER_HUB_USERNAME/todo:${{ github.sha }}
      - run: docker tag $DOCKER_HUB_USERNAME/todo:${{ github.sha }} registry.heroku.com/todo-pdm/web
      - run: docker push registry.heroku.com/todo-pdm/web
      - run: heroku container:release web -a todo-pdm
      - run: sh ./webhook.sh